package com.googlesource.gerrit.plugins.chatgpt.settings;

import java.util.Map;

public class Settings {
    public static final String GERRIT_PATCH_SET_FILENAME = "/PATCHSET_LEVEL";
    public static final String GERRIT_DEFAULT_MESSAGE_DONE = "Done";
    public static final String GERRIT_AUTOGENERATED_PREFIX = "autogenerated:";
    public static final Map<String , String> COMMIT_MESSAGE_FILTER_OUT_PREFIXES = Map.of(
            "PARENT","Parent:",
            "AUTHOR","Author:",
            "AUTHOR_DATE", "AuthorDate:",
            "COMMIT","Commit:",
            "COMMIT_DATE", "CommitDate:",
            "CHANGE_ID", "Change-Id:"
    );
    public static final String GERRIT_COMMIT_MESSAGE_PREFIX = "Subject: ";

    public static final String EMPTY_REVIEW_MESSAGE = "No update to show for this Change Set";

    public enum MODES {
        stateless,
        stateful
    }

}
