package com.googlesource.gerrit.plugins.chatgpt.settings;

public class Settings {
    public static final String GERRIT_PATCH_SET_FILENAME = "/PATCHSET_LEVEL";
    public static final String GERRIT_DEFAULT_MESSAGE_DONE = "Done";
    public static final String GERRIT_AUTOGENERATED_PREFIX = "autogenerated:";
    public static final String EMPTY_REVIEW_MESSAGE = "No update to show for this Change Set";

    public enum MODES {
        stateless,
        stateful
    }

}
